### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by immibis**
- Removed the gem cutter/refiner messaging stuff, since it seemed to be unnecessary, and actually broke things (this was the cause of machines not running until they were right-clicked). Now the main logic only runs on the server, like with most things in Minecraft.
- Removed the energy messaging stuff, because it was unnecessary except for the GUI bars, and inefficient (because it sent packets to everyone in the dimension). Now energy will only be synced while the player has the GUI open.
- Fixed various things not working with "/gamerule doDaylightCycle false", by using the right type of world time.
- Creates less temporary ItemStacks and ArrayLists. It should be more efficient, but I don't know _how much_ of a difference it makes.
- Removed a few methods that weren't actually being used for anything.

Yes, there is some duplicated code; I didn't want to make big changes to the structure of anything to avoid that.

### CODE REVIEW

**Comment by jaredlll08** [comment]
Besides for those, it looks great!
Thanks!

**Comment by jaredlll08** [comment]
And this is the old repo xD, just realized, would it be possible to move the changes to the new one? (If not then I will do it later)

**Comment by immibis** [comment]
@jaredlll08 Not sure. I started this before I found out there was a new repo, so I thought I might as well post it here (since I know it works with this code) and find out what to do.

**Comment by immibis** [comment]
@jaredlll08 by the way, you know that changing the mod ID from fluxedcrystals to fluxedCrystals **deletes all Fluxed Crystals blocks and items from everyone's world**!?

**Comment by jaredlll08** [comment]
I didn't make that change, although noted and will be fixed asap

**Comment by jaredlll08** [comment]
So should I port the fixes over? or are you willing to port it over?

**Comment by immibis** [comment]
@jaredlll08 I'd rather you did it (of course), but if it's my fault for looking in the wrong repository, then I suppose I should.

**Comment by jaredlll08** [comment]
xD if I do it, the. You need to hell me with your eclipse plugin later ;)

**Comment by jaredlll08** [comment]
wow that spelling...

**Comment by immibis** [comment]
@jaredlll08 I've done it, unless I made a mistake, see https://github.com/jaredlll08/Fluxed-Crystals-Reborn/pull/2

**Comment by jaredlll08** [comment]
merged :)

**Comment by jaredlll08** [comment]
sorry about the confusion, and thanks for actually taking an interest in the mod =D

**Pull request merged**
